services:
  minecraft:
    build: .
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - minecraft:/minecraft-server/data
    restart: unless-stopped

volumes:
  minecraft:
